name: Pull Request
on: 
  pull_request:
    branches: main

jobs:
  validate-manifest:
    name: Validate Manifest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Run validation script
        run: |
          node .build/validateManifest.js $SLACK_APP_CONFIG_TOKEN
    env:
      SLACK_APP_CONFIG_TOKEN: ${{ secrets.SLACK_APP_CONFIG_TOKENm}}



