name: Pull Request
on: 
  pull_request:
    branches: main

jobs:
  validate-manifest:
    name: Validate Manifest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      
      - uses: c-hive/gha-yarn-cache@v2
      
      - name: Install dependencies
        run: yarn

      - name: Run validation script
        run: node --loader ts-node/esm .build/validateManifest.ts ${{ secrets.SLACK_APP_CONFIG_TOKEN}}

  validate-serverless:
    name: Validate Serverless Config
    runs-on: ubuntu-latest
    steps:
      - name: Setup credentials
        run: |
          echo $CREDENTIALS >> credentials.json
          echo "::set-env name=CREDENTIALS_PATH::$(pwd)/credentials.json"
        env:
          CREDENTIALS: ${{ secrets.ESTIMATRON_PRODUCTION_CREDENTIALS }}
          
      - uses: actions/checkout@v1

      - name: Validate slack-api/serverless.yml
        uses: serverless/github-action@v3
        with:
          args: -c "cd ./slack-api && serverless info"
          entrypoint: /bin/sh
        



